/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.occs.ldsoft.occs;

public final class Manifest {
    public static final class permission {
        /**  Required 
 Required 
         */
        public static final String JPUSH_MESSAGE="com.occs.ldsoft.occs.permission.JPUSH_MESSAGE";
    }
}
